import json
from pathlib import Path

import pandas as pd
from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.util import Inches, Pt

from .common import FEATURES

APPLE = "https://performance-partners.apple.com/search-api"
ROBOTS = "https://itunes.apple.com/robots.txt"
SKLEARN = "https://scikit-learn.org/stable/modules/cross_validation.html"


def markdown_table(frame, columns=None):
    df = frame[columns] if columns else frame
    fmt = lambda v: f"{v:.3f}" if isinstance(v, float) else str(v).replace("|", "/")
    lines = ["| " + " | ".join(df.columns) + " |", "| " + " | ".join(["---"] * len(df.columns)) + " |"]
    lines += ["| " + " | ".join(fmt(v) for v in row) + " |" for row in df.itertuples(index=False, name=None)]
    return "\n".join(lines)


def report(audit, cv, test_metrics, cases, selected, provenance, output_dir):
    out = Path(output_dir)
    best = test_metrics.set_index("model").loc[selected]
    baseline = test_metrics.set_index("model").loc["Dummy"]
    difference = float(best.f1 - baseline.f1)
    matrix = json.loads((out / "reports/confusion_matrices.json").read_text(encoding="utf-8"))[selected]["matrix"]
    tn, fp = matrix[0]
    statement = (f"{selected}: holdout F1 {best.f1:.3f} vs Dummy {baseline.f1:.3f} "
                 f"(gain {difference:+.3f}); ROC-AUC {best.roc_auc:.3f}. "
                 f"It detected {tn}/{tn + fp} lower-rated apps. "
                 "The F1 gain is descriptive; no statistical significance is claimed.")
    if difference <= 0:
        statement += " The metadata models do not demonstrate an improvement over the majority baseline on F1."
    status = provenance["data_kind"]
    md = f"""# Midterm results
Data status: **{status}**. These metrics are generated by the pipeline, never manually entered.

## Research question
Can seven app metadata attributes distinguish rating >=4.5 from <4.5 among existing US App Store
applications with at least 50 ratings at collection time?

## Data and validation
Eligible apps: {audit['clean_rows']}. Class counts: {audit['class_counts']}.
Collection interval (UTC): {audit['collection_start']} to {audit['collection_end']}.
Fixed stratified 80/20 split, random_state=42. Five-fold stratified CV inside training.
Every imputer, scaler and encoder is fitted inside a Pipeline on the applicable training fold.
No hyperparameter or threshold search was performed. Selection used CV F1 only; ties use model name.

## Cross-validation
F1, precision and recall refer to class 1. Standard deviations are sample SD (ddof=1), not confidence intervals.

{markdown_table(cv, ['model', 'cv_f1_mean', 'cv_f1_std', 'cv_roc_auc_mean', 'cv_roc_auc_std', 'cv_precision_mean', 'cv_recall_mean', 'f1_generalization_gap'])}

See cv_metrics.csv for mean and SD of every metric and cv_folds_metrics.csv for individual folds.

## Fixed holdout
{markdown_table(test_metrics)}
{statement}

A majority predictor can have high positive-class F1 under imbalance. Inspect ROC-AUC, balanced
accuracy and both rows of the confusion matrix. SVM ROC-AUC uses decision scores, not probabilities.
Default classification thresholds are unchanged.

## Real error cases (anonymized)
Cases are selected within each error type by closeness to the rating boundary, then trackId.
The identifiers, names, exact ratings and descriptions are withheld from public reports.
The full audit table is in outputs/private/test_predictions.csv on the machine that ran the study.

{markdown_table(cases) if len(cases) else 'The selected model made no test errors; this is not proof of generalization.'}

These observations do not establish why users assigned a rating.

## Limits
- A query-ranked convenience sample is not a random sample of the App Store.
- The >=50 criterion selects established apps; these results do not predict pre-launch success.
- Features and labels describe a single collection period; app ratings and metadata can change.
- Update recency is a snapshot feature and may reflect a consequence of popularity.
- Multiple apps from the same developer may occur in both splits; a future group/time split is needed.
- CV was used to choose a model, so its winning CV mean can be optimistic; the holdout is untouched by selection.
- Seven metadata features omit usability, bugs, marketing, review text and other possible causes.

## Next phase
Neural network, description/review text analysis and Streamlit are reserved for Final.
Raw descriptions have been captured privately; no text is used in Midterm features.

## Sources
- [Apple Search API]({APPLE})
- [iTunes robots.txt]({ROBOTS}): contains Disallow: /search*, checked 2026-10-08.
- [scikit-learn cross-validation]({SKLEARN})

## Execution provenance
Source commit: {provenance['git_commit']}; Python: {provenance['python_version']};
scikit-learn: {provenance['sklearn_version']}. Dataset fingerprint: {provenance['dataset_sha256']}.
"""
    (out / "reports/results.md").write_text(md, encoding="utf-8")
    card = f"""# Data card
Status: {status}. Source: Apple iTunes Search API, US storefront; software only.
Collection: {audit['collection_start']} to {audit['collection_end']} (UTC).
Instructor conditions are recorded in config/source_approval.json.
Apple describes API content as promotional. The API documentation is not evidence that
robots.txt permits collection: /search* is disallowed there. Instructor approval is course approval,
not a statement about Apple's permission. Raw responses and descriptions must not be published.

## Sampling and provenance
132 interleaved, prespecified keyword queries; pilot uses fitness, education, puzzle game.
Main responses are limited to 200 each; minimum 3.2 seconds between request starts, retries included.
Stop after reaching at least 2,000 eligible distinct apps; require at least 1,500 to train.
Raw bytes, request parameters, timestamp and SHA-256 are stored under ignored data/raw.
Search results overlap and are ranking-biased. The dataset is not representative of all apps.

## Cleaning audit
{json.dumps(audit, indent=2)}

## Decisions
1. Require positive integer trackId, a valid collection timestamp and kind=software.
2. Keep the latest complete observation per trackId (stable source-order tie-break); never mix fields across times.
3. Keep USD rows; do not assume a foreign or unknown currency is dollars.
4. Require an integer userRatingCount >=50 and a finite averageUserRating in [0,5].
5. Define high_rated = int(averageUserRating >=4.5); exactly 4.5 belongs to class 1.
6. Negative price, nonpositive size and malformed values become missing features.
7. fileSizeBytes / 1,000,000 gives decimal MB. Languages are distinct normalized valid codes;
   an explicit empty list means zero, an absent list means missing.
8. Release year before 2008 or after collection is missing. Future updates, and updates preceding
   a valid release, are missing. Recency uses full elapsed days at each row's collection timestamp.
9. Preserve missing features for fold-local imputation; do not fill with global medians.
10. Descriptions remain private for Final. Models see only {', '.join(FEATURES)}.

## Target leakage
averageUserRating forms the label. userRatingCount only filters eligibility.
Neither is a feature. No current-version rating, ID, app name, description or developer ID enters the model.
contentAdvisoryRating is an allowed age-content category, not a user rating.

## Split and storage
data/splits/split.csv preserves track IDs and train/test assignments privately.
The fingerprint detects data changes. Recollection requires a separate run directory and a new reported experiment.
Public outputs are aggregate metrics/figures and anonymized diagnostic cases.
Local runs retain original JSON and models in ignored directories.
Cloud runs retain raw files only for their runner lifetime; their public artifact excludes raw data,
app-level cleaned data, split IDs, models and private predictions. Run locally to keep a private raw archive.
Do not upload these excluded files to this public repository.

Sources: {APPLE}; {ROBOTS}; {SKLEARN}.
"""
    (out / "reports/data_card.md").write_text(card, encoding="utf-8")
    return statement


def presentation(audit, cv, metrics, cases, selected, statement, output_dir, data_kind):
    out = Path(output_dir)
    prs = Presentation()
    prs.slide_width, prs.slide_height = Inches(13.333), Inches(7.5)
    navy, teal, orange = RGBColor.from_string("102A43"), RGBColor.from_string("167D8D"), RGBColor.from_string("E9A23B")
    main_audit_path = out / "reports/main_audit.json"
    actual_requests = (json.loads(main_audit_path.read_text(encoding="utf-8")).get("queries_completed")
                       if main_audit_path.exists() else None)
    sampling_line = (f"{actual_requests} requests used; 132 keywords planned" if actual_requests
                     else "132 keywords planned; up to 200 results/query")

    def box(slide, text, x, y, w, h, size=24, bold=False, color=navy):
        shape = slide.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
        tf = shape.text_frame
        tf.word_wrap = True
        for index, line in enumerate(text.split("\n")):
            p = tf.paragraphs[0] if index == 0 else tf.add_paragraph()
            p.text = line
            p.font.name = "Aptos"
            p.font.size = Pt(size)
            p.font.bold = bold
            p.font.color.rgb = color
            p.space_after = Pt(14)
        return shape

    def slide(title, notes):
        s = prs.slides.add_slide(prs.slide_layouts[6])
        box(s, title, .55, .35, 12.2, .8, 30, True)
        box(s, f"APP STORE ML / MIDTERM     •     {len(prs.slides):02d} / 09", .6, 7.06, 12, .25, 10, color=teal)
        if data_kind != "real_api":
            box(s, "SYNTHETIC TEST • NOT RESEARCH RESULTS", .6, 6.68, 12, .3, 16, True, orange)
        s.notes_slide.notes_text_frame.text = notes
        return s

    s = slide("Can metadata identify highly rated apps?",
              "0:00–0:50. Introduce binary classification among existing apps with 50+ ratings. "
              "We are not predicting app success before launch. Explain label threshold.")
    box(s, "Existing US App Store apps\nClass 1: rating ≥ 4.5\nClass 0: rating < 4.5", .7, 1.65, 8.7, 3.2, 32, True)
    box(s, f"{audit['clean_rows']:,}\neligible apps", 9.7, 2.0, 3, 2, 31, True, teal)
    box(s, "Seven metadata inputs · Four classifiers · Fixed holdout", .7, 5.7, 12, .6, 22)

    s = slide("Data source and collection conditions",
              "0:50–1:50. Describe instructor conditions and the robots.txt discrepancy. "
              "Do not say robots.txt allows collection. Explain keyword sampling and overlap. "
              f"Sources: {APPLE} and {ROBOTS}. Raw data stays private.")
    box(s, f"Apple iTunes Search API · US storefront\n{sampling_line}\n"
        "Pause ≥3.2 seconds; cache raw responses privately\nLatest observation per trackId; at least 50 ratings",
        .7, 1.5, 12, 3.8, 25)
    box(s, "robots.txt disallows /search* • Raw JSON/descriptions stay private", .7, 5.65, 12, .8, 21, True, teal)

    s = slide("Cleaning and class balance",
              "1:50–2:50. Explain minimum sample size, invalid values, duplicates and class imbalance. "
              "The right chart previews comparison with a baseline; detailed metrics follow.")
    s.shapes.add_picture(str(out / "figures/overview.png"), Inches(.65), Inches(1.45), width=Inches(12))
    box(s, f"Raw rows: {audit['raw_rows']:,} → eligible unique apps: {audit['clean_rows']:,}", .8, 6.05, 11.8, .5, 22)

    s = slide("Seven inputs; rating fields are excluded",
              "2:50–3:40. Explain age content category versus user rating. Dates are measured at collection. "
              "Descriptions are captured only for the later text-analysis phase.")
    box(s, "price_usd · size_mb · primary_genre\ncontent_advisory_rating · language_count\n"
        "release_year · update_recency_days", .7, 1.6, 12, 2.6, 29, True)
    box(s, "averageUserRating → target only\nuserRatingCount → ≥50 eligibility filter only",
        .7, 4.65, 12, 1.5, 26, color=teal)

    s = slide("Validation without data leakage",
              "3:40–4:40. Explain the permanent 80/20 split and five folds within train. "
              "Model choice uses mean CV F1. No tuning against test. Fixed hyperparameters were declared in advance. "
              f"Reference: {SKLEARN}")
    box(s, "Stratified 80/20 split · random_state = 42\nFive-fold stratified CV within train\n"
        "Fold-local imputation → encoding/scaling → model\n"
        "Dummy · Decision Tree · KNN · SVM\n"
        f"Selected by mean CV F1: {selected}", .7, 1.4, 12, 4.7, 25)

    s = slide("Results: F1 needs a baseline",
              "4:40–5:50. Compare CV mean/SD and fixed-test metrics. "
              "SD is fold variation, not a confidence interval. Explain why majority prediction can have high F1. "
              + statement)
    columns = ["Model", "CV F1 ± SD", "Test F1", "AUC", "Precision", "Recall"]
    table = s.shapes.add_table(5, 6, Inches(.6), Inches(1.6), Inches(12.1), Inches(2.8)).table
    for column, width in zip(table.columns, [2.3, 2.7, 1.75, 1.65, 1.85, 1.85]):
        column.width = Inches(width)
    for j, label in enumerate(columns):
        table.cell(0, j).text = label
    for i, row in enumerate(cv.itertuples(index=False), 1):
        test_row = metrics.set_index("model").loc[row.model]
        values = [row.model, f"{row.cv_f1_mean:.3f} ± {row.cv_f1_std:.3f}",
                  f"{test_row.f1:.3f}", f"{test_row.roc_auc:.3f}",
                  f"{test_row.precision:.3f}", f"{test_row.recall:.3f}"]
        for j, value in enumerate(values):
            cell = table.cell(i, j)
            cell.text = value
    for i in range(5):
        for j in range(6):
            for p in table.cell(i, j).text_frame.paragraphs:
                p.font.size = Pt(18)
    box(s, statement, .7, 4.95, 12, 1.6, 20)

    s = slide("Where predictions fail",
              "5:50–6:50. Rows are actual classes, columns predictions. Explain FP and FN. "
              "Compare majority-class behavior to the selected model. Use ROC-AUC alongside F1.")
    s.shapes.add_picture(str(out / "figures/confusion_matrices.png"), Inches(2.65), Inches(1.2),
                        height=Inches(5.55))

    s = slide("Real cases, anonymized",
              "6:50–7:50. These are actual test errors with identifying raw fields removed. "
              "Cases nearest the 4.5 boundary are selected deterministically within FP and FN. "
              "Discuss plausible limitations, not unproven causes.")
    shown_cases = pd.concat([cases.loc[cases.error_type.eq(kind)].head(1) for kind in ["FP", "FN"]])
    lines = [f"{r.case} · {r.error_type} · true {r.actual_class}, predicted {r.predicted_class}\n{r.observation}"
             for r in shown_cases.itertuples(index=False)]
    box(s, "\n\n".join(lines) if lines else "No errors for the selected model in this holdout.",
        .7, 1.45, 12, 4.9, 22)
    box(s, "Full private audit is generated locally; public cases omit IDs, names and exact ratings.",
        .7, 6.35, 12, .5, 15, color=teal)

    s = slide("Conclusion and next steps",
              "7:50–9:00. State the numerical finding honestly, including when baseline wins. "
              "Limit claims to existing US apps with 50+ ratings. Discuss future developer-group and temporal splits. "
              "Neural networks, text features and Streamlit are for Final.")
    box(s, statement, .7, 1.45, 12, 1.7, 23, True)
    box(s, "Limits: search-ranking bias, one snapshot, developer overlap\n"
        "No evidence for pre-launch success prediction\n"
        "Final: neural network · text analysis · Streamlit", .7, 3.55, 12, 2.6, 25)
    destination = out / "midterm.pptx"
    prs.save(destination)
    if len(Presentation(destination).slides) != 9:
        raise AssertionError("Presentation must contain 9 slides.")
    return destination
